work on search db

diff --git a/scripts/make-search-index b/scripts/make-search-index
--- a/scripts/make-search-index
+++ b/scripts/make-search-index
@@ -16,11 +16,17 @@ fi
 
 tmsu init
 
+tmsu tag -c arch =x86_64 =portable \
+  needs-cpp needs-ctest-io needs-libc \
+  needs-libc-linkage needs-libc-headers
+
 tmsu imply c89 c99
 tmsu imply c99 c11
+tmsu imply needs-libc needs-libc-linkage
+tmsu imply needs-libc needs-libc-headers
+tmsu imply needs-libc needs-ctest-io 
 tmsu imply needs-libc-linkage needs-ctest-io
 tmsu imply needs-libc-headers needs-cpp
-tmsu tag -c arch =x86_64 =portable
 
 
 for suite in single-exec
@@ -51,6 +57,15 @@ n=$(tmsu files "$q" | wc -l)
 if test "$n" != "0"
 then
     echo "Tests without a specified standard, aborting:"
+    tmsu files "$q"
+    exit 1
+fi
+
+q="not arch"
+n=$(tmsu files "$q" | wc -l)
+if test "$n" != "0"
+then
+    echo "Tests a specified arch, aborting:"
     tmsu files "$q"
     exit 1
 fi
